import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from './(component)/navbar/page'
import Home from './page'
import Footer from './(component)/footer/page'
import { SpeedInsights } from "@vercel/speed-insights/next"

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: "Personal  Portfolio Project",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon-32x32.png" }],
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      
      <body className={inter.className}>

    <div className='fixed w-full z-10 bg-white shadow-md ' > <Navbar />  </div> 
    <div  className='pt-20'>{children}</div>
     <div>  <Footer  /></div>


    </body> 
                
    </html>
  )
}
